# Generated by Django 5.2.4 on 2025-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('review_text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
